name: Create Manual Release

on:
  workflow_dispatch: # This allows manual triggering via the UI

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to create a release and upload assets

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          filename: 'release.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig'

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          files: release.zip
          tag_name: latest-build  # Using a constant tag name
          name: Latest Stable Build
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
